version: '3.2'
services:
  app:
    container_name: app
    build:
      context: ./app
    restart: unless-stopped
    ports:
      - '3001:3001'
      - '9663:9662'
    volumes:
      - ./app:/app
    depends_on:
      back:
        condition: service_started

  back_start:
    container_name: back_start
    build:
      context: ./back/local
      dockerfile: ./Dockerfile.start
    volumes:
      - ./back:/app
    depends_on:
      db:
        condition: service_started

  back:
    container_name: back
    build:
      context: ./back/local
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '9662:9662'
    volumes:
      - ./back:/app
    depends_on:
      db:
        condition: service_started
      back_start:
        condition: service_completed_successfully

  db:
    image: 'mariadb:10.5'
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=main
    volumes:
      - app_database_volume:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  app_database_volume:
